/**
 * Created by Administrator on 2016-11-21.
 */
db.movie.insert({
    movies:[ {
        url:'<img src="/images/首页/12.jpg">',
        chinaName:'奇异博士',
        englishName:'Doctor Strange',
        type:'d动作，冒险，奇幻',
        time:'美国/115分钟',
        playTime:'2016-11-04大陆上映',
        introduce:'影片讲述了神经外科医生斯特兰奇因一次车祸失去了双手工作的能力，最终在法师帮助下拥有了超凡的能力，' +
        '并对抗黑暗力量的故事。出色的外科手术专家史蒂芬·斯特兰奇（本尼迪克特·康伯巴奇 饰）本来事业有成，但在遭遇一次车祸悲剧后，' +
        '双手再也无法握住手术刀，不能继续他的医生职业,为治疗手伤远赴尼泊尔的他在机缘巧合下遇到了莫度男爵（切瓦特·埃加福特 饰），' +
        '在莫度男爵推动下他得到了至尊魔法师（蒂尔达·斯文顿 饰）的帮助。斯特兰奇把自己曾经的自负都抛在了一边，开始接触和学习鲜为人知的玄学、' +
        '以及多维空间世界的学问。在纽约的格林威治村，变身奇异博士的斯特兰奇，化身为现实世界和多维空间的中间人，他利用超自然能力和神器来' +
        '保护世界不被魔法和神秘力量侵袭。',
        directorPic:'<img src="/images/首页/奇异博士/18.jpg">',
        directorName:'斯科特.德瑞克森',
        actorPicOne:'<img src="/images/首页/奇异博士/3.jpg">',
        actorOne:'本尼迪克特.康...',
        actorPicTwo:'<img src="/images/首页/奇异博士/5.jpg">',
        actorTwo:'切瓦特.埃加福特',
        actorPicThree:'<img src="/images/首页/奇异博士/1.jpg">',
        actorThree:'秋瑞.麦克亚当斯..',
        actorPicFour:'<img src="/images/首页/奇异博士/2.jpg">',
        actorFour:'本尼迪特.王'
    },
        {
            url:'<img src="">',
            chinaName:'阿拉丁与神灯',
            englishName:'Les Nouvelles Aventures dAladin',
            type:'喜剧，爱情',
            time:'法国/101分钟',
            playTime:'2016-11-18大陆上映',
            introduce:'影片讲述了神经外科医生斯特兰奇因一次车祸失去了双手工作的能力，最终在法师帮助下拥有了超凡的能力，' +
            '并对抗黑暗力量的故事。出色的外科手术专家史蒂芬·斯特兰奇（本尼迪克特·康伯巴奇 饰）本来事业有成，但在遭遇一次车祸悲剧后，' +
            '双手再也无法握住手术刀，不能继续他的医生职业,为治疗手伤远赴尼泊尔的他在机缘巧合下遇到了莫度男爵（切瓦特·埃加福特 饰），' +
            '在莫度男爵推动下他得到了至尊魔法师（蒂尔达·斯文顿 饰）的帮助。斯特兰奇把自己曾经的自负都抛在了一边，开始接触和学习鲜为人知的玄学、' +
            '以及多维空间世界的学问。在纽约的格林威治村，变身奇异博士的斯特兰奇，化身为现实世界和多维空间的中间人，他利用超自然能力和神器来' +
            '保护世界不被魔法和神秘力量侵袭。',
            directorPic:'<img src="">',
            directorName:'斯科特.德瑞克森',
            actorPicOne:'<img src="">',
            actorOne:'本尼迪克特.康...',
            actorPicTwo:'<img src="">',
            actorTwo:'切瓦特.埃加福特',
            actorPicThree:'<img src="">',
            actorThree:'秋瑞.麦克亚当斯..',
            actorPicFour:'<img src="">',
            actorFour:'本尼迪特.王'
        },
        {
            chinaName:'白云桥',
            englishName:'Brideg in Clouds',
            type:'恐怖,惊悚,悬疑',
            time:'中国大陆 / 94分钟',
            playTime:"2016-11-18大陆上映",
            introduce:'事起源于浙江余姚有1300多年历史的著名古建筑白云桥，此桥经常出现一半晴空一半云雾的灵异现象，相传是连接阴阳两界的桥梁，人在桥上可与鬼魂进行交流。孟妍（钟萱 饰）于午夜子时，在白云桥上遇见了一个小男孩（李卓霖 饰），小男孩引领她进入了另一个空间——“中阴界”。小男孩告诉孟妍一个惊天的秘密， 事关她与张青（温兆伦 饰）的夫妻关系和性命安危。孟妍将信将疑又陷入痛苦和焦虑，小男孩的预言一一应验，孟妍陷入崩溃的边缘，唯有到那阴森神秘的白云桥去寻找答案……',
            url:'<img src="./images/0b5e98a4b7044cc7e445da18c460e104373854.jpg">',
            directorPic:'<img src="./images/643fc0987b4a78e70208b0b90e543c1636793.jpg">',
            directorName:"钟萱",
            actorPicOne:'<img src="./imgges/643fc0987b4a78e70208b0b90e543c1636793.jpg">',
            actorOne:'钟萱饰：孟妍',
            actorPicTwo:'<img src="./imgges/979bba3edf5dc6efeb1b13d5bd10c5c035832.jpg">',
            actorTwo:'温兆伦饰：张青',
            actorPicThree:'<img src="./imgges/b46e43b4619c8f20588f03315a8fa63e11958.jpg">',
            actorThree:'刘宇珽饰：红衣女（阴魄）',
            actorPicFour:'<img src="./imgges/9f176b8e8cc2d0d1fd4aac99a48eaaa533876.jpg">',
            actorFour:'夏望饰：王小天',
        },
        {
            chinaName:'你的名字',
            englishName:'your name',
            type:'剧情/爱情/奇幻',
            time:'日本/120分钟',
            playTime:"2016-12-02",
            introduce:'影片讲述了一名少年和一名少女在梦中相遇邂逅的奇幻爱情故事。在千年一遇的彗星造访地球的一个月前，身居日本深山小镇的少女宫水三叶（上白石萌音 配音）每天都过着忧郁烦燥的生活，而正处于青春叛逆期的她对大都市的憧憬向往与日俱增。然而不久，三叶做了一个变成男孩子的梦，眼前的这里有着陌生的房间、朋友和她梦寐以求的宽敞街道。三叶虽然感到迷茫困惑，但能够尽情享受朝思暮想的都市生活的她觉得神清气爽。与此同时，远在他乡的东京少年立花泷（神木隆之介 配音）也有一个奇怪的梦境，睁开睡眼的他发现变成一名不知名姓女孩的自己身处一个从未去过的深山小镇。两人惊醒时发现各自回到了自己的身体，但每逢两人入睡或半梦半醒之际，他们就会交换对调身份。一头雾水的三叶决定循着线索找寻立花泷，而立花泷也试着跟三叶沟通，冥冥之中互换身份的两人不约而同地竭尽所能设法找寻对方，而彼此间的了解也因此渐渐加深，虽未曾相见却早已似曾相识的两人暗生情愫，一段青春季节的奇妙物语随之展开。跨越时空梦境的阻隔，终在现实世界邂逅的两人上演了一幕青涩浪漫的奇遇暖心之恋。岂料一场突如其来的意外将两人的一切美好定格在梦醒之际……',
            url:'<img src="./images/910b2e6c7cb0da947d65ef5c33929eb9366676.jpg">',
            directorPic:'<img src="./images/3e35c91e812e5c00f6d35162ac25604d33076.jpg">',
            directorName:"新海诚",
            actorPicOne:'<img src="./imgges/ccb502a78ad450fb83554f1c36c5869331161.jpg">',
            actorOne:'上白石萌音饰：三叶（日语配音）',
            actorPicTwo:'<img src="./imgges/5a995164858cbc247dc33e89b24e5cbc44413.jpg">',
            actorTwo:'神木隆之介饰：公泷（日语配音）.',
            actorPicThree:'<img src="./imgges/9c5225d1ba025e5c24f6e9e668b805ad82627.jpg">',
            actorThree:'长泽雅美',
            actorPicFour:'<img src="./imgges/512ecd10ff8c35ed454263e410090e4f24428.jpg">',
            actorFour:'市原悦子',
        },
        {
            url:'<img src="/images/首页/19.jpg">',
            chinaName:'神奇动物在哪里',
            englishName:'Fantastic Beasts and Where to Find T... ',
            type:'冒险,奇幻,家庭',
            time:'英国,美国/133分钟',
            playTime:'2016-11-25大陆上映',
            directorPic:'<img src="/images/详情/神气动物在哪里/22.jpg">',
            director:'大卫.叶茨',
            actorPicOne:'<img src="/images/详情/神气动物在哪里/7.jpg">',
            actorOne:'埃迪.雷德梅恩',
            actorPicTwo:'<img src="/images/详情/神气动物在哪里/18.jpg">',
            actorTwo:'凯瑟琳.沃特斯顿',
            actorPicThree:'<img src="/images/详情/神气动物在哪里/8.jpg">',
            actorThree:'艾莉森.萨多尔',
            actorPicFour:'<img src="/images/详情/神气动物在哪里/16.jpg">',
            actorFour:'丹. 福勒',
            introduce:'影片讲述了神奇动物学家纽特·斯卡曼德因在纽约城发生的一次意外而不得不去寻找从魔法箱里脱逃的珍奇异兽而展开的冒险' +
            '旅程。1926年，纽约城魔法世界风起云涌。多个神秘物体在城中大肆破坏，令魔法界陷入了被誓要铲除魔法师的激进灭魔组织“第二' +
            '塞勒姆”发现的危机之中。而史上最危险的黑巫师盖勒特·格林德沃在欧洲造成灾难毁灭性的破坏后，失去踪影。刚完成环球游历之旅' +
            '且身怀绝技的神奇动物学家纽特·斯卡曼德（埃迪·雷德梅恩 饰）并未察觉到危机，抵达了他原本只想短暂停留驻足的纽约城。他在旅' +
            '途中研究并拯救珍奇魔法动物，有一部分更被收集进了他那个看似普通无奇却暗藏玄机，并作为全球珍稀和濒危神奇动物的保护栖息地' +
            '的魔法手提皮箱。对魔法一无所知的灭魔组织成员雅各布（丹·福勒 饰）意外将斯卡曼德藏在皮箱的奇兽释放到气氛紧张的纽约城中，' +
            '严重违反了国际巫师联合会保密法。前正气师蒂娜（凯瑟琳·沃特森 饰）插手事件，意图恢复职位。可是事情的进展并不顺利，美国魔' +
            '法政府机构美利坚魔法国会高深莫测的魔法安全部部长格雷夫斯（柯林·法瑞尔 饰）更将矛头指向斯卡曼德和蒂娜。现在身处同一阵线' +
            '的斯卡曼德和蒂娜，与蒂娜的妹妹一名法术高超的摄念师奎妮（艾莉森·苏朵儿 饰）及灭魔组织成员雅各布携手，在那些走失的奇兽作' +
            '恶前找回它们。但事件远比他们想像中更加凶险，被卷入黑暗力量的他们，将魔法世界和灭魔组织引向了开战边缘......'
        },
        {
            url:'<img src="/images/首页/1.jpg">',
            chinaName:'我不是潘金莲',
            englishName:'I Am Not Madame Bovary',
            type:'剧情,喜剧',
            time:'中国大陆/140分钟',
            playTime:'2016-11-18大陆上映',
            introduce:'影片讲述一个普通的农村妇女李雪莲（范冰冰 饰），为了纠正一句话，与上上下下、方方面面打了十年交道。打交道的过程中，' +
            '她没想到一件事变成了另一件事，接着变成了第三件事。十年过去，她没有把这句话纠正过来，但她饱尝了世间的人情冷暖，悟明白了' +
            '另外一个道理。李雪莲要纠正的这句话是她前夫说的。她前夫说：“你是李雪莲吗？我咋觉得你是潘金莲呢？”李雪莲要告诉大家的是：' +
            '我不是潘金莲。',
            directorPic:'<img src="/images/详情/我不是潘金莲/10.jpg">',
            director:'冯小刚',
            actorPicOne:'<img src="/images/详情/我不是潘金莲/15.jpg">',
            actorOne:'范冰冰',
            actorPicTwo:'<img src="/images/详情/我不是潘金莲/28.jpg">',
            actorTwo:'郭涛',
            actorPicThree:'<img src="/images/详情/我不是潘金莲/24.jpg">',
            actorThree:'董成鹏',
            actorPicFour:'<img src="/images/详情/我不是潘金莲/17.jpg">',
            actorFour:'张嘉译'
        }

    ],
    seat:[
        {rowId:1, colId:1, displayId:'1排1座', status:0, seatId:1},
        {rowId:1, colId:2, displayId:'1排2座', status:0, seatId:2},
        {rowId:1, colId:3, displayId:'1排3座', status:0, seatId:3},
        {rowId:1, colId:4, displayId:'1排4座', status:0, seatId:4},
        {rowId:1, colId:5, displayId:'1排5座', status:0, seatId:5},
        {rowId:1, colId:6, displayId:'1排6座', status:0, seatId:6},
        {rowId:1, colId:7, displayId:'1排7座', status:0, seatId:7},
        {rowId:1, colId:8, displayId:'1排8座', status:0, seatId:8},
        {rowId:1, colId:9, displayId:'1排9座', status:0, seatId:9},
        {rowId:1, colId:10, displayId:'1排10座', status:0, seatId:10},
        {rowId:2, colId:1, displayId:'2排1座', status:0, seatId:11},
        {rowId:2, colId:2, displayId:'2排2座', status:0, seatId:12},
        {rowId:2, colId:3, displayId:'2排3座', status:0, seatId:13},
        {rowId:2, colId:4, displayId:'2排4座', status:0, seatId:14},
        {rowId:2, colId:5, displayId:'2排5座', status:0, seatId:15},
        {rowId:2, colId:6, displayId:'2排6座', status:0, seatId:16},
        {rowId:2, colId:7, displayId:'2排7座', status:0, seatId:17},
        {rowId:2, colId:8, displayId:'2排8座', status:0, seatId:18},
        {rowId:2, colId:9, displayId:'2排9座', status:0, seatId:19},
        {rowId:2, colId:10, displayId:'2排10座', status:0, seatId:20},
        {rowId:3, colId:1, displayId:'3排1座', status:0, seatId:21},
        {rowId:3, colId:2, displayId:'3排2座', status:0, seatId:22},
        {rowId:3, colId:3, displayId:'3排3座', status:0, seatId:23},
        {rowId:3, colId:4, displayId:'3排4座', status:0, seatId:24},
        {rowId:3, colId:5, displayId:'3排5座', status:0, seatId:25},
        {rowId:3, colId:6, displayId:'3排6座', status:0, seatId:26},
        {rowId:3, colId:7, displayId:'3排7座', status:0, seatId:27},
        {rowId:3, colId:8, displayId:'3排8座', status:0, seatId:28},
        {rowId:3, colId:9, displayId:'3排9座', status:0, seatId:29},
        {rowId:3, colId:10, displayId:'3排10座', status:0, seatId:30},
        {rowId:4, colId:1, displayId:'4排1座', status:0, seatId:31},
        {rowId:4, colId:2, displayId:'4排2座', status:0, seatId:32},
        {rowId:4, colId:3, displayId:'4排3座', status:0, seatId:33},
        {rowId:4, colId:4, displayId:'4排4座', status:0, seatId:34},
        {rowId:4, colId:5, displayId:'4排5座', status:0, seatId:35},
        {rowId:4, colId:6, displayId:'4排6座', status:0, seatId:36},
        {rowId:4, colId:7, displayId:'4排7座', status:0, seatId:37},
        {rowId:4, colId:8, displayId:'4排8座', status:0, seatId:38},
        {rowId:4, colId:9, displayId:'4排9座', status:0, seatId:39},
        {rowId:4, colId:10, displayId:'4排10座', status:0, seatId:40},
        {rowId:5, colId:1, displayId:'5排1座', status:0, seatId:41},
        {rowId:5, colId:2, displayId:'5排2座', status:0, seatId:42},
        {rowId:5, colId:3, displayId:'5排3座', status:0, seatId:43},
        {rowId:5, colId:4, displayId:'5排4座', status:0, seatId:44},
        {rowId:5, colId:5, displayId:'5排5座', status:0, seatId:45},
        {rowId:5, colId:6, displayId:'5排6座', status:0, seatId:46},
        {rowId:5, colId:7, displayId:'5排7座', status:0, seatId:47},
        {rowId:5, colId:8, displayId:'5排8座', status:0, seatId:48},
        {rowId:5, colId:9, displayId:'5排9座', status:0, seatId:49},
        {rowId:5, colId:10, displayId:'5排10座', status:0, seatId:50},
        {rowId:6, colId:1, displayId:'6排1座', status:0, seatId:51},
        {rowId:6, colId:2, displayId:'6排2座', status:0, seatId:52},
        {rowId:6, colId:3, displayId:'6排3座', status:0, seatId:53},
        {rowId:6, colId:4, displayId:'6排4座', status:0, seatId:54},
        {rowId:6, colId:5, displayId:'6排5座', status:0, seatId:55},
        {rowId:6, colId:6, displayId:'6排6座', status:0, seatId:56},
        {rowId:6, colId:7, displayId:'6排7座', status:0, seatId:57},
        {rowId:6, colId:8, displayId:'6排8座', status:0, seatId:58},
        {rowId:6, colId:9, displayId:'6排9座', status:0, seatId:59},
        {rowId:6, colId:10, displayId:'6排10座', status:0, seatId:60},
        {rowId:7, colId:1, displayId:'7排1座', status:0, seatId:61},
        {rowId:7, colId:2, displayId:'7排2座', status:0, seatId:62},
        {rowId:7, colId:3, displayId:'7排3座', status:0, seatId:63},
        {rowId:7, colId:4, displayId:'7排4座', status:0, seatId:64},
        {rowId:7, colId:5, displayId:'7排5座', status:0, seatId:65},
        {rowId:7, colId:6, displayId:'7排6座', status:0, seatId:66},
        {rowId:7, colId:7, displayId:'7排7座', status:0, seatId:67},
        {rowId:7, colId:8, displayId:'7排8座', status:0, seatId:68},
        {rowId:7, colId:9, displayId:'7排9座', status:0, seatId:69},
        {rowId:7, colId:10, displayId:'7排10座', status:0, seatId:70},
        {rowId:8, colId:1, displayId:'8排1座', status:0, seatId:71},
        {rowId:8, colId:2, displayId:'8排2座', status:0, seatId:72},
        {rowId:8, colId:3, displayId:'8排3座', status:0, seatId:73},
        {rowId:8, colId:4, displayId:'8排4座', status:0, seatId:74},
        {rowId:8, colId:5, displayId:'8排5座', status:0, seatId:75},
        {rowId:8, colId:6, displayId:'8排6座', status:0, seatId:76},
        {rowId:8, colId:7, displayId:'8排7座', status:0, seatId:77},
        {rowId:8, colId:8, displayId:'8排8座', status:0, seatId:78},
        {rowId:8, colId:9, displayId:'8排9座', status:0, seatId:79},
        {rowId:8, colId:10, displayId:'8排10座', status:0, seatId:80},
        {rowId:9, colId:1, displayId:'9排1座', status:0, seatId:81},
        {rowId:9, colId:2, displayId:'9排2座', status:0, seatId:82},
        {rowId:9, colId:3, displayId:'9排3座', status:0, seatId:83},
        {rowId:9, colId:4, displayId:'9排4座', status:0, seatId:84},
        {rowId:9, colId:5, displayId:'9排5座', status:0, seatId:85},
        {rowId:9, colId:6, displayId:'9排6座', status:0, seatId:86},
        {rowId:9, colId:7, displayId:'9排7座', status:0, seatId:87},
        {rowId:9, colId:8, displayId:'9排8座', status:0, seatId:88},
        {rowId:9, colId:9, displayId:'9排9座', status:0, seatId:89},
        {rowId:9, colId:10, displayId:'9排10座', status:0, seatId:90},
        {rowId:10, colId:1, displayId:'10排1座', status:0, seatId:91},
        {rowId:10, colId:2, displayId:'10排2座', status:0, seatId:92},
        {rowId:10, colId:3, displayId:'10排3座', status:0, seatId:93},
        {rowId:10, colId:4, displayId:'10排4座', status:0, seatId:94},
        {rowId:10, colId:5, displayId:'10排5座', status:0, seatId:95},
        {rowId:10, colId:6, displayId:'10排6座', status:0, seatId:96},
        {rowId:10, colId:7, displayId:'10排7座', status:0, seatId:97},
        {rowId:10, colId:8, displayId:'10排8座', status:0, seatId:98},
        {rowId:10, colId:9, displayId:'10排9座', status:0, seatId:99},
        {rowId:10, colId:10, displayId:'10排10座', status:0, seatId:100}
    ]
});